ARG NEXUS_VERSION="3.58.1"
ARG NEXUS_IMAGE_NAME="nexus3"
ARG IMAGE_NEXUS_TAG="docker.io/sonatype/${NEXUS_IMAGE_NAME}:${NEXUS_VERSION}"

ARG PUBLISHED_SOURCE_URL=https://github.com/leadof/leadof
ARG PUBLISHED_DOCUMENTATION_URL=https://github.com/leadof/leadof#readme

ARG NEXUS_ADMIN_DEFAULT_PASSWORD

FROM ${IMAGE_NEXUS_TAG}

ARG NEXUS_ADMIN_DEFAULT_PASSWORD

COPY ./nexus.properties /nexus-data/etc/nexus.properties

RUN echo ${NEXUS_ADMIN_DEFAULT_PASSWORD} > /nexus-data/admin.password

LABEL org.opencontainers.image.documentation ${PUBLISHED_DOCUMENTATION_URL}
LABEL org.opencontainers.image.source ${PUBLISHED_SOURCE_URL}
LABEL org.opencontainers.image.description "A ready-made Nexus server for optimizing dependency management like containers, node, etc."
