.PHONY: repo
repo:
	@gh repo create leadof/leadof \
		--clone \
		--description "A curated collection of leadership resources." \
		--disable-issues \
		--disable-wiki \
		--license "UNLICENSED" \
		--public \
		--push \
		--source "./"
