name: "upgrade-podman"
description: "Upgrades podman on the default GitHub Actions runner"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        podman --version

        sudo apt-get update -qq

        DEBIAN_FRONTEND=noninteractive sudo apt-get remove -qqy podman

        sudo mkdir -p /etc/apt/keyrings

        # Debian Testing/Bookworm
        curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Testing/Release.key \
          | gpg --dearmor \
          | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg]\
            https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Testing/ /" \
          | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null

        sudo apt-get update -qq

        # Upgrade packages
        sudo apt-get -qqy upgrade

        # Install Podman
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -qqy --no-install-recommends podman

        podman --version
