ARG ALPINE_VERSION=3.14
ARG IMAGE_TAG=docker.io/alpine:${ALPINE_VERSION}

ARG PUBLISHED_SOURCE_URL=https://github.com/leadof/leadof
ARG PUBLISHED_DOCUMENTATION_URL=https://github.com/leadof/leadof#readme

FROM ${IMAGE_TAG}

ARG PUBLISHED_SOURCE_URL
ARG PUBLISHED_DOCUMENTATION_URL

RUN mkdir --parents /usr/src/libraries/ \
  && mkdir --parents /usr/src/dist/

COPY . /usr/src/libraries/

WORKDIR /usr/src/

# archive and compress
# cleanup source
RUN tar -czvf /usr/src/dist/libraries_shell-scripts.tar.gz ./libraries/shell/

VOLUME [ "/usr/src/libraries/", "/usr/src/dist/" ]

LABEL org.opencontainers.image.documentation ${PUBLISHED_DOCUMENTATION_URL}
LABEL org.opencontainers.image.source ${PUBLISHED_SOURCE_URL}
LABEL org.opencontainers.image.description "The application script libraries."
