FROM docker.io/library/node:18.16.0-alpine3.16 as base

RUN npm config set fund false --global && npm install --location=global npm && npm install --location=global pnpm

FROM base as dev_dependencies

RUN mkdir -p /tmp/dependencies/

WORKDIR /tmp/dependencies/

COPY ./package.json .

RUN pnpm install

FROM base as build

WORKDIR /usr/src/app/

COPY . .

COPY --from=dev_dependencies /tmp/dependencies/ /usr/src/app/

RUN pnpm build:ssr

# TODO: copy build output only
FROM base as production

ENV PORT=4000
ENV NODE_ENV=production

WORKDIR /usr/src/app/

COPY --from=build /usr/src/app/dist/app/ /usr/src/app/dist/app/

CMD ["node", "/usr/src/app/dist/app/server/main.js"]
