ARG PUBLISHED_SOURCE_URL=https://github.com/leadof/leadof
ARG PUBLISHED_DOCUMENTATION_URL=https://github.com/leadof/leadof#readme

FROM localhost/leadof/node as node

################################################################################
# Layer target: node with chrome browser
################################################################################
FROM node as node_chrome

ARG PUBLISHED_SOURCE_URL
ARG PUBLISHED_DOCUMENTATION_URL

WORKDIR /tmp/

USER root

RUN apt-get update --quiet \
  && DEBIAN_FRONTEND=noninteractive apt-get install --quiet --yes --no-install-recommends wget ca-certificates \
  && wget --no-verbose https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
  && DEBIAN_FRONTEND=noninteractive apt-get install --quiet --yes --no-install-recommends ./google-chrome-stable_current_amd64.deb \
  && rm --force ./google-chrome-stable_current_amd64.deb \
  # clean up docker layer
  # https://docs.docker.com/develop/develop-images/dockerfile_best_practices/#run
  && rm --recursive --force /var/lib/apt/lists/*

USER node

ENV CHROME_BIN=/usr/bin/google-chrome

LABEL org.opencontainers.image.documentation ${PUBLISHED_DOCUMENTATION_URL}
LABEL org.opencontainers.image.source ${PUBLISHED_SOURCE_URL}
LABEL org.opencontainers.image.description "NodeJS and the Google Chrome browser for web browser automation"
