ARG ALPINE_VERSION="3.14"
ARG BASE_IMAGE_TAG="docker.io/alpine:${ALPINE_VERSION}"

################################################################################
# Layer target: Smallest image
################################################################################
FROM ${BASE_IMAGE_TAG} as smol

RUN mkdir --parents /usr/src/

WORKDIR /usr/src/
