################################################################################
# Continuous integration for libraries container.
################################################################################
name: containers.libraries.ci

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/containers.libraries.ci.yaml"
      - "src/containers/libraries/**"
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
    paths:
      - ".github/workflows/containers.libraries.ci.yaml"
      - "src/containers/libraries/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CI: true
  CONTAINER_DEPLOY_NAME: "libraries"

jobs:
  integrate:
    # This name appears in status checks for pull requests and branch protection.
    name: containers.libraries.ci

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup-task-execution
        uses: ./.github/actions/setup-task-execution/
        with:
          container-registry-password: ${{ secrets.GH_PACKAGES_WRITE_TOKEN }}

      - name: make
        working-directory: ./src/containers/libraries/
        env:
          PUBLISHED_SOURCE_URL: https://github.com/leadof/leadof
          PUBLISHED_DOCUMENTATION_URL: https://github.com/leadof/leadof#readme
        run: make

      - name: upload-task-output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: task-output
          path: "**/.task-output/"
          if-no-files-found: error
