################################################################################
# Continuous integration for node container.
################################################################################
name: containers.node.ci

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/containers.node.ci.yaml"
      - "src/containers/node/**"
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
    paths:
      - ".github/workflows/containers.node.ci.yaml"
      - "src/containers/node/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  integrate:
    # This name appears in status checks for pull requests and branch protection.
    name: containers.node.ci

    runs-on: ubuntu-latest

    steps:
      - name: setup-task-execution
        uses: ./.github/actions/setup-task-execution/

      - name: build
        working-directory: ./src/containers/node/
        env:
          PUBLISHED_SOURCE_URL: https://github.com/leadof/leadof
          PUBLISHED_DOCUMENTATION_URL: https://github.com/leadof/leadof#readme
        run: make deploy
