################################################################################
# Continuous integration for leadof.us web application.
################################################################################
name: apps.leadof-us.ci

on:
  workflow_run:
    workflows: [apps.leadof-us.dependencies.ci]
    types: [completed]
  push:
    branches: [main]
    paths:
      # run this build when this file changes
      - ".github/workflows/leadof-us.ci.yaml"
      # run this build when the source code changes
      - "src/apps/leadof-us/**"
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
    paths:
      # run this build when this file changes
      - ".github/workflows/leadof-us.ci.yaml"
      # run this build when the source code changes
      - "src/apps/leadof-us/**"

  # Enable manual trigger for workflow.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  integrate:
    # This name appears in status checks for pull requests and branch protection.
    name: apps.leadof-us.ci

    runs-on: ubuntu-latest

    steps:
      - name: setup-task-execution
        uses: ./.github/actions/setup-task-execution/

      - name: Make
        working-directory: ./src/apps/leadof-us/
        run: make

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./src/apps/leadof-us/test-results/
          if-no-files-found: error
