################################################################################
# Continuous integration for leadof.us web application.
################################################################################
name: apps.leadof-us.ci

on:
  workflow_run:
    workflows: [apps.leadof-us.dependencies.ci]
    types: [completed]
  push:
    branches: [main]
    paths:
      # run this build when this file changes
      - ".github/workflows/leadof-us.ci.yaml"
      # run this build when the source code changes
      - "src/apps/leadof-us/**"
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
    paths:
      # run this build when this file changes
      - ".github/workflows/leadof-us.ci.yaml"
      # run this build when the source code changes
      - "src/apps/leadof-us/**"

  # Enable manual trigger for workflow.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CI: true
  PUBLISHED_SOURCE_URL: https://github.com/leadof/leadof
  PUBLISHED_DOCUMENTATION_URL: https://github.com/leadof/leadof#readme

jobs:
  integrate:
    # This name appears in status checks for pull requests and branch protection.
    name: apps.leadof-us.ci

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup-task-execution
        uses: ./.github/actions/setup-task-execution/
        with:
          container-registry-password: ${{ secrets.GH_PACKAGES_WRITE_TOKEN }}

      - name: make
        working-directory: ./src/apps/leadof-us/
        run: make ci

      - name: upload-task-output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: task-output
          path: "**/.task-output/"
          if-no-files-found: error
