################################################################################
# Continuous integration for leadof.us web application.
################################################################################
name: apps.leadof-us.ci

on:
  push:
    branches: [main]
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
    paths:
      # run this build when this file changes
      - ".github/workflows/leadof-us.ci.yaml"
      # run this build when the source code changes
      - "src/apps/leadof-us/**"

  # Enable manual trigger for workflow.
  workflow_dispatch:

env:
  CI: true
  PROJECT_PATH: ./src/apps/leadof-us/

jobs:
  integrate:
    # This name appears in status checks for pull requests and branch protection.
    name: apps.leadof-us.ci

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install libraries
        run: make install-libraries

      - name: Make
        # change to the project directory
        working-directory: ${{ env.PROJECT_PATH }}
        run: make

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ${{ env.PROJECT_PATH }}test-results/
          if-no-files-found: error
