################################################################################
# Continuous integration for leadof.us web application.
################################################################################
name: apps.leadof-us.ci

on:
  push:
    branches: [main]
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
    paths:
      # run this build when this file changes
      - ".github/workflows/leadof-us.ci.yaml"
      # run this build when the source code changes
      - "src/apps/leadof-us/**"

  # Enable manual trigger for workflow.
  workflow_dispatch:

env:
  CI: true
  PROJECT_PATH: ./src/apps/leadof-us/

jobs:
  integrate:
    # This name appears in status checks for pull requests and branch protection.
    name: apps.leadof-us.ci

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Upgrade podman
        run: |
          podman --version

          sudo apt-get update -qq

          DEBIAN_FRONTEND=noninteractive sudo apt-get remove -qqy podman

          sudo mkdir -p /etc/apt/keyrings

          # Debian Testing/Bookworm
          curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Testing/Release.key \
            | gpg --dearmor \
            | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg]\
              https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Testing/ /" \
            | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null

          sudo apt-get update -qq

          # Upgrade packages
          sudo apt-get -qqy upgrade

          # Install Podman
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -qqy --no-install-recommends podman

          podman --version

      - name: Executable scripts
        run: |
          chmod +x ./src/libraries/shell/executable
          . ./src/libraries/shell/executable

      - name: Install containers
        run: make install-containers

      - name: Install libraries
        run: make install-libraries

      - name: Make
        # change to the project directory
        working-directory: ${{ env.PROJECT_PATH }}
        run: make

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ${{ env.PROJECT_PATH }}test-results/
          if-no-files-found: error
