################################################################################
# Checks the repository.
################################################################################
name: repository.ci

on:
  push:
    branches: [main]
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

  # Enable manual trigger for workflow.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CI: true
  # Should match ".nvmrc" file.
  NODE_VERSION: 18.16.0
  # Should match ".pnpm-version" file.
  PNPM_VERSION: 8.6.1

jobs:
  integrate:
    # This name appears in status checks for pull requests and branch protection.
    name: repository.ci

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup the environment with a specific version of NodeJS.
      - name: Install node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Setup the environment with a specific version of `pnpm`.
      - name: Install pnpm ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      # Determine where `pnpm` will store files in order to cache them.
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      # Setup the `pnpm` cache.
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Make
        run: |
          chmod +x ./prerequisites.sh
          make ci
