################################################################################
# Checks the repository.
################################################################################
name: repository.ci

on:
  push:
    branches: [main]
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

  # Enable manual trigger for workflow.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CI: true
  PUBLISHED_SOURCE_URL: https://github.com/leadof/leadof
  PUBLISHED_DOCUMENTATION_URL: https://github.com/leadof/leadof#readme

jobs:
  integrate:
    # This name appears in status checks for pull requests and branch protection.
    name: repository.ci

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup-task-execution
        uses: ./.github/actions/setup-task-execution/
        with:
          container-registry-password: ${{ secrets.GH_PACKAGES_WRITE_TOKEN }}

      - name: check-repository
        run: pnpm container:check:repository

      - name: upload-task-output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: task-output
          path: "**/.task-output/"
          if-no-files-found: error
