################################################################################
# Checks the repository.
################################################################################
name: repository.ci

on:
  push:
    branches: [main]
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

  # Enable manual trigger for workflow.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  integrate:
    # This name appears in status checks for pull requests and branch protection.
    name: repository.ci

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup-task-execution
        uses: ./.github/actions/setup-task-execution/
        with:
          container-registry-password: ${{ secrets.GH_PACKAGES_WRITE_TOKEN }}

      - name: Make
        run: make ci

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results/
          if-no-files-found: error
