################################################################################
# Checks the repository.
################################################################################
name: repository.ci

on:
  push:
    branches: [main]
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

  # Enable manual trigger for workflow.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CI: true
  # Should match ".nvmrc" file.
  NODE_VERSION: 18.16.1
  # Should match ".pnpm-version" file.
  PNPM_VERSION: 8.6.5
  CONTAINER_REGISTRY_USERNAME: ${{ github.actor }}
  CONTAINER_REGISTRY_PASSWORD_FILE_PATH: ./GH_PACKAGES_WRITE_TOKEN

jobs:
  integrate:
    # This name appears in status checks for pull requests and branch protection.
    name: repository.ci

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup-wireit
        uses: ./.github/actions/setup-wireit/

      - name: executable-shell-scripts
        uses: ./.github/actions/executable-shell-scripts/

      - name: Make
        run: |
          printf "${{ secrets.GH_PACKAGES_WRITE_TOKEN }}" >> ${CONTAINER_REGISTRY_PASSWORD_FILE_PATH}
          make ci

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ${{ env.PROJECT_PATH }}test-results/
          if-no-files-found: error
